In [32]:
#Numerical Python as numpy
import numpy as np
myarr = np.array([[1,2,3,4],
                 [1,2,34,4]])
zeros = np.zeros((2,4))
ones = np.ones((2,4))
empty = np.empty((2,4))
arrange = np.arange(12)
arrange.reshape(3,4)
linspace = np.linspace(1,6,5)
oneDarray = np.arange(15)
twoDarray = oneDarray.reshape(3,5)
threeDarray = np.arange(27).reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [66]:
np.amin(myarr)
np.amin(myarr,axis=0)
np.max(myarr)
np.amax(myarr,axis=0)
rs = np.median(myarr)
print(rs)
deg = np.array([0,30,45,60,90])
np.sin(deg+np.pi/180)

2.5


array([ 0.01745241, -0.98518908,  0.85994206, -0.3213861 ,  0.88604054])

In [37]:
hello = np.array([[1,2,3,4],[5,6,7,8]])
hello.shape
hello.ndim

2

In [49]:
arr = np.array([x for x in range(1,10)])
arr.reshape(3,-1) #dynamic sizing
arr.reshape(-1) #flaten the array
a = np.array([1,2,3])
b = np.array([4,5,6])
np.add(a,b)
np.subtract(b,a)
np.multiply(a,b)
np.divide(b,a)
np.power(a,2)

array([1, 4, 9], dtype=int32)

In [55]:
#conditional logic
x = np.array([i for i in range(10)])
np.where(x%2==0, 'Even', 'Odd')
a = [x<5,x>5]
b = [x++2,x++3]
np.select(a,b)

array([ 2,  3,  4,  5,  6,  0,  9, 10, 11, 12])

In [78]:
#indexing and slicing numpy
array_1d = np.array([1,2,3,4])
array_2d = np.array([[1,2,3,4],
                     [5,6,7,8]])
array_3d = np.array([[[1,2,3,4],
                      [5,6,7,8],
                      [9,1,2,3]]])
print(array_1d[0])
print(array_2d[1,-1]) 
print(array_3d[0,2,-1])
print(array_1d[1:])
print(array_2d[1,1:])
print(array_3d[0,1:,1:])

1
8
3
[2 3 4]
[6 7 8]
[[6 7 8]
 [1 2 3]]
